### ISSUE TITLE
消息没有收到

### ISSUE THREAD

**Issue by liubei1** [iflamed/cordova-huawei-push#3]
我的插件导入成功APP ID和包名都加上了   打包也正常，但是客户端收不到消息是什么原因呢？
`cordova.plugins.huaweipush.init();`这段代码也执行了  没有报错。
![image](https://cloud.githubusercontent.com/assets/15815777/23845616/2bbb225c-0804-11e7-8afa-98d8c62c674b.png)
就是这些push的消息没有收到  需要其他的处理么？

**Comment by iflamed** [comment]
看起来发送数为0，你可以看到adb logcat 里面的日志吗？TAG是： HuaweiPushPlugin

**Comment by iflamed** [comment]
也有可能是后续行为直接打开应用的问题，你选择自定义行为试一试呢？自定义行为，一定要传参数，华为hms 自定义行为不传参数，好像也无法生效。

**Comment by zhaoxiaoming99** [comment]
我们也遇到了同样的问题，看起来注册成功了，也能拿到token的值，可是通过控制台发送推送消息就是收不到，跟上面截图一样，数目都是0.
还有为什么控制台发送push消息需要输入手机IMEI呢？在什么地方可以看到我的这个app有多少客户端注册了消息订阅呢？

**Comment by iflamed** [comment]
建议使用adb  调试一下看看，调试记录里面会有华为推送库的日志信息。

**Comment by DimRed** [comment]
一样的问题. 后面怎么解决的?

**Comment by chenwynn** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
LorisC, @randomishwalk, @ykari, @jurajselep, @gulbaki, @abdullah-ming, @Bilg4me, @tkalp, @SonnyCastro, @lrqstudy, @donniesworld13, @sschueller, @mahad53, @SunshineKPa, @majorisgit, @iceycode, @aweeraman, @LHerskind, @toklok, @hehe2046
